spring.application.name=16_SOM_VEASNA_PVH_SPRING_Homework003
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_homework003
spring.datasource.username=postgres
spring.datasource.password=112233
